version: '3'

services:
  web:
    container_name: 'api'
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: "mongodb://localhost:27017"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app/
    depends_on:
      - 'mongo'
    networks: 
      - backend

  mongo:
      image: 'mongo:latest'
      container_name: 'mongodb'
      ports:
        - '27017:27017'
      networks: 
        - backend

networks:
  backend: 