version: '3'

services:
  api:
    container_name: keepsafe_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "${API_PORT:-8080}:8080"
    env_file:
      - ./.env
    networks:
      - local_network
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
      image: 'mongo:latest'
      container_name: 'keepsafe_mongodb'
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-root}
      ports:
        - '27017:${MONGO_PORT:-27017}'
      volumes:
        - mongo:/data/db
      healthcheck:
        test: echo 'db.runCommand("ping").ok'
        interval: 10s
        timeout: 10s
        retries: 5
        start_period: 40s
      networks:
        - local_network

networks:
  local_network:
    driver: bridge

volumes:
    mongo: