POST http://localhost:8080 HTTP/1.1
content-type: application/json

{
    "text": "valid_text"
}

###

GET http://localhost:8080 HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/65ff6e867cd4dd69858afca7/ HTTP/1.1
content-type: application/json

{
}


###

GET http://localhost:8080/65ff6e967cd4dd69858afca8/ HTTP/1.1
content-type: application/json

{
}


###

PUT http://localhost:8080/65ff6e967cd4dd69858afca8/ HTTP/1.1
content-type: application/json

{
    "text": "valid_text"
}