POST http://localhost:8080 HTTP/1.1
content-type: application/json

{
    "text": "valid_text"
}

###

GET http://localhost:8080 HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/65ff6e847cd4dd69858afca6/ HTTP/1.1
content-type: application/json

{
}


###

GET http://localhost:8080/65ff7430bf93655963c20878/ HTTP/1.1
content-type: application/json

{
}